// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Helion
{
    internal sealed partial class Vsix
    {
        public const string Id = "Helion.e1e706e2-05d3-4da9-8754-652cd8ab65f4";
        public const string Name = "Helion";
        public const string Description = @"A dark mode theme for Visual Studio 2026.";
        public const string Language = "en-US";
        public const string Version = "1.0.33";
        public const string Author = "Brandon Gandy";
        public const string Tags = "theme, dark";
        public const bool IsPreview = false;
    }
}
